server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            classpath:config/,
            classpath:config/licensingservice,
            classpath:config/organizationservice,
            classpath:config/specialroutesservice,
            classpath:config/zuulservice,
            classpath:config/authenticationservice

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
